---
- name: Open port 9090 (Ubuntu)
  ufw:
    rule: allow
    port: 9090
    proto: tcp
    state: enabled
  when: ansible_distribution == "Ubuntu"

- name: Allow Prometheus for Firewall (CentOS)
  firewalld:
    port: 9090/tcp
    permanent: yes
    state: enabled
  when: ansible_distribution == "CentOS"

- name: Install Prometheus (Ubuntu)
  apt:
    name: prometheus
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install Prometheus (CentOS)
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.30.0/prometheus-2.30.0.linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root
  when: ansible_distribution == "CentOS"

- name: install apache2 (Ubuntu)
  apt:
    name: apache2
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install apache (CentOS)
  dnf:
    name: httpd
    state: latest
  when: ansible_distribution == "CentOS"
